import Head from "next/head";
import React from "react";

const CustomHead = ({ title }: { title: string }) => (
  <Head>
    <title>Movie | {title}</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);

export default CustomHead;
